import Head from 'next/head'
import { Inter } from 'next/font/google'
import { YearCard } from '@/components/YearCard'
import { Header } from '@/components/header'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Good Games 🎮</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="App">
          <Header />
          <YearCard year={'2022'} />
          <YearCard year={'2021'} />
          <YearCard year={'2020'} />
        </div>

      </main>
    </>
  )
}
